# Generated by Django 4.2.5 on 2023-10-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('propic', models.FileField(default='defaultuser.png', upload_to='user_profile/')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
